[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_SUPABASE_URL = "https://xaohatfpnsoszduxgdyp.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhhb2hhdGZwbnNvc3pkdXhnZHlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyOTMxMzIsImV4cCI6MjA3Mjg2OTEzMn0.Sv3HsfTQ5X_o8EEpptwUsP1SCp1BdSHPe8qBomVJn3k"
  VITE_SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhhb2hhdGZwbnNvc3pkdXhnZHlwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NzI5MzEzMiwiZXhwIjoyMDcyODY5MTMyfQ._7UR1-L1Jx4YQz-bgp9u_vU-7UHqimt_ErakI9av6cI"
  VITE_ADMIN_EMAIL = "admin@edessa.com"
  VITE_APP_NAME = "Generador de Clientes - EDESSA"
  VITE_DEFAULT_SHEET_NAME = "CLIENTES SIN VENT MULTICATEGORI"
